#!/bin/bash
# commits_list.sh: Generates an HTML page listing the last 20 commits,
# each linking to a detail page generated by commit_show.sh.

# Ensure we're in a Git repository
if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo "Error: Not inside a Git repository."
  exit 1
fi

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATES_DIR="$BASE_DIR/templates"

# Write to a persistent file (commits_list.html) in the base directory
OUTPUT_FILE="$BASE_DIR/commits_list.html"

# Start with header
cat "$TEMPLATES_DIR/header.html" > "$OUTPUT_FILE"
# Insert commits_list template content
cat "$TEMPLATES_DIR/commits_list.html" >> "$OUTPUT_FILE"

# Generate commit items (last 20 commits)
{
  echo '<div class="list-group mt-3">'
  git log -n 20 --pretty=format:'%h|%s|%an|%ad' --date=short | while IFS='|' read -r hash subject author date; do
    # Define the output filename for the commit detail page
    COMMIT_FILE="$BASE_DIR/commit_show_$hash.html"
    # Pre-generate the commit detail page if it does not exist
    if [ ! -f "$COMMIT_FILE" ]; then
      "$BASE_DIR/lib/commit_show.sh" "$hash" "$COMMIT_FILE"
    fi
    # Link to the generated commit detail HTML file
    echo "  <a href=\"$COMMIT_FILE\" class=\"list-group-item list-group-item-action\">"
    echo "    <strong>$hash</strong> - $subject<br>"
    echo "    <small>$author, $date</small>"
    echo "  </a>"
  done
  echo '</div>'
} >> "$OUTPUT_FILE"

# End with footer
cat "$TEMPLATES_DIR/footer.html" >> "$OUTPUT_FILE"

echo "Generated commits list: $OUTPUT_FILE"
xdg-open "$OUTPUT_FILE" 2>/dev/null || open "$OUTPUT_FILE" 2>/dev/null
